apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: pipelineruns.run.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: run.com
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: pipelineruns
    # singular name to be used as an alias on the CLI and for display
    singular: pipelinerun
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: PipelineRun
    listKind: PipelineRunList
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - pr
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                count:
                  type: integer
---
apiVersion: "run.com/v1alpha1"
kind: TaskRun
metadata:
  name: tr-updated
spec:
  message: "Task Runsssss"
  count: 3
---